### PR TITLE
Introduces the bugfix command

### PR DESCRIPTION
**Pull request by angelkar**
### Bugfix-start, bugfix-close
To avoid seconds thoughts among devs, I think, when opening a bugfix, it would be simpler and clearer to type

`oneflow bugfix-start foo` instead of `oneflow feature-start foo`

Under the hood, it's the same command as `feature-start` :)

### Display help if no arguments given
More than one people, were left wondering for a couple of seconds, if they typed just the `oneflow` command. So, displaying help doesn't harm.

### Copywriting improvements
More elaborate description when running commands

### CODE REVIEW

**Comment by nikostoulas** [comment]
Nice work @angelkar !
However bugfix-start close seems more like a Workable conversion to me.
Do you think it makes sense in [oneflows](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) model?
I would argue that https://github.com/Workable/oneflow/issues/37 with a default feature prefix that could be overwritten with a bugfix prefix would make more sense. Wdyt?

**Comment by angelkar** [comment]
I guess it's a matter of preference and habit. No strong opinion held here.

Adding orefix automatically is definitely an improvement though.

**Comment by nikostoulas** [comment]
I would suggest to keep the first and last commit for now for this to be merged. And let's discuss offline about the bugfix command.

**Comment by nikostoulas** [comment]
I like the configurable version:
- The 2 new commands will only be available if BUGFIX_PREFIX is set
- In a future PR, BUGFIX_PREFIX and FEATURE_PREFIX will be respected
Wdyt?

**Comment by angelkar** [comment]
Best of both worlds. I like it.

**Comment by angelkar** [comment]
Kind reminder. Should we merge this?

**Comment by nikostoulas** [comment]
new version v1.5.0

**Pull request merged**
